
     // @ts-nocheck
    // oxlint-disable
   // oxfmt-ignore
  // ⚠️  Auto-generated by bini-router — do not edit.

import React, { Suspense } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';

const Layout0 = React.lazy(() => import('@/app/layout'));
const NotFound = React.lazy(() => import('@/app/not-found'));
const Loading = React.lazy(() => import('@/app/loading'));
const Page0 = React.lazy(() => import('@/app/page'));
const Page1 = React.lazy(() => import('@/app/rdc'));
const Page2 = React.lazy(() => import('@/app/cart'));
const Page3 = React.lazy(() => import('@/app/admin'));
const Page4 = React.lazy(() => import('@/app/audit'));
const Page5 = React.lazy(() => import('@/app/login'));
const Page6 = React.lazy(() => import('@/app/route'));
const Page7 = React.lazy(() => import('@/app/orders'));
const Page8 = React.lazy(() => import('@/app/review'));
const Page9 = React.lazy(() => import('@/app/manager'));
const Page10 = React.lazy(() => import('@/app/privacy'));
const Page11 = React.lazy(() => import('@/app/product'));
const Page12 = React.lazy(() => import('@/app/profile'));
const Page13 = React.lazy(() => import('@/app/reports'));
const Page14 = React.lazy(() => import('@/app/checkout'));
const Page15 = React.lazy(() => import('@/app/messages'));
const Page16 = React.lazy(() => import('@/app/products'));
const Page17 = React.lazy(() => import('@/app/register'));
const Page18 = React.lazy(() => import('@/app/tracking'));
const Page19 = React.lazy(() => import('@/app/wishlist'));
const Page20 = React.lazy(() => import('@/app/logistics'));
const Page21 = React.lazy(() => import('@/app/questions'));
const Page22 = React.lazy(() => import('@/app/deliveries'));
const Page23 = React.lazy(() => import('@/app/rdc-orders'));
const Page24 = React.lazy(() => import('@/app/manage-users'));
const Page25 = React.lazy(() => import('@/app/rdc-tracking'));
const Page26 = React.lazy(() => import('@/app/manage-orders'));
const Page27 = React.lazy(() => import('@/app/order-success'));
const Page28 = React.lazy(() => import('@/app/forgot-password'));
const Page29 = React.lazy(() => import('@/app/logistic-orders'));
const Page30 = React.lazy(() => import('@/app/manage-products'));

// ─── Error Boundary ───────────────────────────────────────────────────────────

class ErrorBoundary extends React.Component<
  { children: React.ReactNode },
  { error: Error | null }
> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) { return { error }; }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    if (import.meta.env.DEV) {
      window.dispatchEvent(new CustomEvent('__bini_error__', {
        detail: { name: error.name, message: error.message, stack: error.stack, componentStack: errorInfo.componentStack, _type: 'runtime' }
      }));
    }
  }
  override render() {
    if (this.state.error) {
      if (import.meta.env.DEV) return null;
      return (
        <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui,sans-serif', padding: '2rem' }}>
          <div style={{ maxWidth: 480, width: '100%', textAlign: 'center' }}>
            <h2 style={{ color: '#e74c3c', marginBottom: '1rem' }}>Something went wrong</h2>
            <pre style={{ background: '#fef2f2', padding: '1rem', borderRadius: '0.5rem', textAlign: 'left', fontSize: '0.8rem', color: '#e74c3c', overflow: 'auto' }}>{this.state.error.toString()}</pre>
            <button onClick={() => this.setState({ error: null })} style={{ marginTop: '1rem', padding: '0.5rem 1.5rem', background: '#00CFFF', color: 'white', border: 'none', borderRadius: '0.5rem', cursor: 'pointer', fontWeight: 600 }}>
              Try again
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}




function TitleSetter({ title }: { title: string }) {
  React.useEffect(() => { document.title = title; }, [title]);
  return null;
}



export default function App() {
  return (
    <BrowserRouter basename={"/"}>
      <Routes>
        <Route element={<><TitleSetter title={"Island Link"} /><Suspense fallback={<Loading />}><ErrorBoundary><Layout0><Outlet /></Layout0></ErrorBoundary></Suspense></>}>
          <Route path="/" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page0 /></ErrorBoundary></Suspense>} />
          <Route path="/rdc" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page1 /></ErrorBoundary></Suspense>} />
          <Route path="/cart" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page2 /></ErrorBoundary></Suspense>} />
          <Route path="/admin" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page3 /></ErrorBoundary></Suspense>} />
          <Route path="/audit" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page4 /></ErrorBoundary></Suspense>} />
          <Route path="/login" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page5 /></ErrorBoundary></Suspense>} />
          <Route path="/route" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page6 /></ErrorBoundary></Suspense>} />
          <Route path="/orders" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page7 /></ErrorBoundary></Suspense>} />
          <Route path="/review" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page8 /></ErrorBoundary></Suspense>} />
          <Route path="/manager" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page9 /></ErrorBoundary></Suspense>} />
          <Route path="/privacy" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page10 /></ErrorBoundary></Suspense>} />
          <Route path="/product" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page11 /></ErrorBoundary></Suspense>} />
          <Route path="/profile" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page12 /></ErrorBoundary></Suspense>} />
          <Route path="/reports" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page13 /></ErrorBoundary></Suspense>} />
          <Route path="/checkout" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page14 /></ErrorBoundary></Suspense>} />
          <Route path="/messages" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page15 /></ErrorBoundary></Suspense>} />
          <Route path="/products" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page16 /></ErrorBoundary></Suspense>} />
          <Route path="/register" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page17 /></ErrorBoundary></Suspense>} />
          <Route path="/tracking" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page18 /></ErrorBoundary></Suspense>} />
          <Route path="/wishlist" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page19 /></ErrorBoundary></Suspense>} />
          <Route path="/logistics" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page20 /></ErrorBoundary></Suspense>} />
          <Route path="/questions" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page21 /></ErrorBoundary></Suspense>} />
          <Route path="/deliveries" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page22 /></ErrorBoundary></Suspense>} />
          <Route path="/rdc-orders" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page23 /></ErrorBoundary></Suspense>} />
          <Route path="/manage-users" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page24 /></ErrorBoundary></Suspense>} />
          <Route path="/rdc-tracking" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page25 /></ErrorBoundary></Suspense>} />
          <Route path="/manage-orders" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page26 /></ErrorBoundary></Suspense>} />
          <Route path="/order-success" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page27 /></ErrorBoundary></Suspense>} />
          <Route path="/forgot-password" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page28 /></ErrorBoundary></Suspense>} />
          <Route path="/logistic-orders" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page29 /></ErrorBoundary></Suspense>} />
          <Route path="/manage-products" element={<Suspense fallback={<Loading />}><ErrorBoundary><Page30 /></ErrorBoundary></Suspense>} />
        </Route>
        <Route path="*" element={          <><TitleSetter title={"Island Link"} /><Layout0>            <Suspense fallback={<Loading />}><ErrorBoundary><NotFound /></ErrorBoundary></Suspense></Layout0></>} />
      </Routes>
    </BrowserRouter>
  );
}
